# image: alpine
# image: python:3.6
# services:
#     - postgres:9.5

# test:
#     variables:
#         THINGS_DB_HOST: postgres
#     script:
#         - echo pass

# before_script:
#     - pip install -r requirements.txt

stages:
    - deploy

pages:
    stage: deploy
    image: node:8.9
    script:
        - curl -o- -L https://yarnpkg.com/install.sh | bash
        - yarn
        - yarn run build
        - cp -r dist/* staticfiles/
        - mv staticfiles public
    artifacts:
        paths:
            - public
    only:
        - master
