version: '3'

services:
    db:
        image: postgres:9.6.5
        restart: always
        environment:
            POSTGRES_DB: bigshort

            # ports:
            # port- 5432:5432
    web:
        command: /code/bin/web
        build:
            context: .
            dockerfile: bigshort/Dockerfile
        environment:
            DATABASE_URL: postgres://postgres:@db:5432/bigshort
        ports:
            - "8000:8000"
        depends_on:
            - db
        volumes:
            - .:/code
    node:
        build:
            context: .
            dockerfile: src/Dockerfile
        ports:
            - "3000:3000"
        volumes:
            - .:/code

