version: '3'

services:
    db:
        image: postgres:9.6.9
        restart: always
        environment:
            POSTGRES_DB: {{cookiecutter.project_name}}

            # ports:
            # port- 5432:5432
    web:
        command: /code/bin/web
        build:
            context: .
            dockerfile: {{cookiecutter.project_name}}/Dockerfile
        environment:
            DATABASE_URL: postgres://postgres:@db:5432/{{cookiecutter.project_name}}
        ports:
            - "8000:8000"
        depends_on:
            - db
        volumes:
            - .:/code

              #     node:
              #         build:
              #             context: .
              #             dockerfile: src/Dockerfile
              #         ports:
              #             - "3000:3000"
              #         volumes:
              #             - .:/code
              #
